-- Reserved schema for T2-T5. No catalog/preview/export implementation is implied.
CREATE TABLE products (id TEXT PRIMARY KEY, site_id TEXT NOT NULL REFERENCES sites(id), source_id TEXT NOT NULL, first_seen_at TEXT NOT NULL, first_eligible_at TEXT, eligibility_rule_ref TEXT, latest_observation_id TEXT, latest_available_version_id TEXT, latest_complete_version_id TEXT, UNIQUE(site_id,source_id));
CREATE TABLE observations (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id), product_id TEXT NOT NULL REFERENCES products(id), attempt INTEGER NOT NULL, revision INTEGER NOT NULL, observed_at TEXT NOT NULL, fields_json TEXT NOT NULL, date_evidence_json TEXT NOT NULL, UNIQUE(run_id,product_id,attempt,revision));
CREATE TABLE product_versions (id TEXT NOT NULL, revision INTEGER NOT NULL, product_id TEXT NOT NULL REFERENCES products(id), manifest_digest TEXT NOT NULL, manifest_json TEXT NOT NULL, PRIMARY KEY(id,revision), UNIQUE(product_id,manifest_digest,revision));
CREATE TABLE assets (id TEXT PRIMARY KEY, root_id TEXT NOT NULL REFERENCES storage_roots(id), relative_path TEXT NOT NULL, sha256 TEXT NOT NULL, bytes INTEGER NOT NULL, state TEXT NOT NULL, verified_at TEXT NOT NULL, journal_id TEXT UNIQUE REFERENCES archive_journal(id), format TEXT, width INTEGER, height INTEGER, UNIQUE(root_id,relative_path));
CREATE TABLE version_images (version_id TEXT NOT NULL, revision INTEGER NOT NULL, source_image_id TEXT NOT NULL, source_url TEXT NOT NULL, ordinal INTEGER NOT NULL, asset_id TEXT REFERENCES assets(id), PRIMARY KEY(version_id,revision,source_image_id), FOREIGN KEY(version_id,revision) REFERENCES product_versions(id,revision));
CREATE TABLE product_user_state (product_id TEXT PRIMARY KEY REFERENCES products(id), favorite INTEGER NOT NULL DEFAULT 0, excluded INTEGER NOT NULL DEFAULT 0, category_override TEXT, revision INTEGER NOT NULL DEFAULT 1, viewed_at TEXT, seen_version_id TEXT, seen_version_revision INTEGER, seen_content_digest TEXT);
CREATE TABLE view_events (event_id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), version_id TEXT NOT NULL, version_revision INTEGER NOT NULL, viewed_at TEXT NOT NULL);
CREATE TABLE site_runs (run_id TEXT NOT NULL REFERENCES runs(id), site_id TEXT NOT NULL REFERENCES sites(id), coverage_json TEXT NOT NULL, PRIMARY KEY(run_id,site_id));
CREATE TABLE discovery_pages (run_id TEXT NOT NULL REFERENCES runs(id), site_id TEXT NOT NULL REFERENCES sites(id), pass INTEGER NOT NULL, page INTEGER NOT NULL, cursor TEXT, signature TEXT NOT NULL, evidence_json TEXT NOT NULL, PRIMARY KEY(run_id,site_id,pass,page));
CREATE TABLE export_jobs (id TEXT PRIMARY KEY, request_key TEXT NOT NULL UNIQUE, state TEXT NOT NULL, snapshot_json TEXT NOT NULL, promised_coverage_json TEXT NOT NULL, required_coverage_json TEXT NOT NULL, capability_notes_json TEXT NOT NULL, output_hash TEXT);
CREATE TABLE export_members (export_id TEXT NOT NULL REFERENCES export_jobs(id), product_id TEXT NOT NULL REFERENCES products(id), snapshot_json TEXT NOT NULL, PRIMARY KEY(export_id,product_id));
CREATE TABLE export_assets (export_id TEXT NOT NULL REFERENCES export_jobs(id), asset_id TEXT NOT NULL REFERENCES assets(id), snapshot_json TEXT NOT NULL, PRIMARY KEY(export_id,asset_id));
CREATE TABLE maintenance_jobs (id TEXT PRIMARY KEY, kind TEXT NOT NULL, state TEXT NOT NULL, snapshot_json TEXT NOT NULL);
CREATE TABLE issues (id TEXT PRIMARY KEY, run_id TEXT REFERENCES runs(id), code TEXT NOT NULL, retryable INTEGER NOT NULL, evidence_ref TEXT NOT NULL);
